//! Tier B harnesses — generated TypeScript plugin/extension files.
//!
//! Each generated file spawns `stateroot hook <event> --harness <id>` via
//! `node:child_process.execFile`, forwarding the plugin's event payload on
//! stdin. Files are plain-JS-compatible TypeScript, self-contained (no
//! external type imports), with binary resolution `STATEROOT_BIN` first,
//! then PATH. Event/API shapes extracted from the ai-memory source:
//!
//! - opencode (`~/.config/opencode/plugins/ai-memory.ts`):
//!   `export const …: Plugin = async ({ directory }) => ({ event, "chat.message",
//!   "tool.execute.before", "tool.execute.after", "experimental.session.compacting",
//!   dispose })` (`install_hooks.rs:1939-2031`).
//! - OMP (`~/.omp/agent/extensions/ai-memory.ts`):
//!   `export default function …(api: any) { api.on("session_start"|"before_agent_start"
//!   |"tool_call"|"tool_result"|"session_before_compact"|"session_shutdown", …) }`
//!   (`install_hooks.rs:2508-2560`).
//! - Pi (`~/.pi/agent/extensions/ai-memory.ts`): same extension form with the
//!   `pi` argument (`install_hooks.rs:2165-2167`).
//!
//! Idempotency: a `# stateroot managed` marker header; only absent or
//! marker-carrying files are (re)written — foreign plugin files are left alone.

use std::path::Path;

use super::registry::HarnessQuirk;
use super::{io_err, HarnessError};

/// Marker header identifying stateroot-managed plugin files.
const MANAGED_MARKER: &str = "// stateroot managed";

/// The target file for a Tier B harness, home-relative.
pub fn ts_plugin_path(quirk: &HarnessQuirk) -> Option<&'static str> {
    match quirk.id {
        "opencode" => Some(".config/opencode/plugins/stateroot.ts"),
        "omp" => Some(".omp/agent/extensions/stateroot.ts"),
        "pi" => Some(".pi/agent/extensions/stateroot.ts"),
        _ => None,
    }
}

/// Render the plugin source for a Tier B harness.
pub fn render_ts_plugin(quirk: &HarnessQuirk) -> String {
    let mut out = format!(
        "// Auto-generated by `stateroot install` — {MANAGED_MARKER}. Edit by re-running, not by hand.\n\
         // StateRoot lifecycle hooks for {} (resume, capture, checkpoint).\n\
         import {{ execFile }} from \"node:child_process\";\n\n\
         function staterootBin(): string {{\n  \
         return process.env.STATEROOT_BIN || \"stateroot\";\n\
         }}\n\n\
         function hook(event: string, payload: unknown): void {{\n  \
         try {{\n    \
         const child = execFile(\n      \
         staterootBin(),\n      \
         [\"hook\", event, \"--harness\", \"{}\"],\n      \
         {{ timeout: 5000 }},\n      \
         () => {{}},\n    \
         );\n    \
         child.stdin?.write(JSON.stringify(payload ?? {{}}));\n    \
         child.stdin?.end();\n  \
         }} catch (_e) {{\n    \
         // Best-effort capture. Hooks must never block the agent.\n  \
         }}\n\
         }}\n\n",
        quirk.display, quirk.id
    );
    match quirk.id {
        "opencode" => out.push_str(OPENCODE_BODY),
        "omp" | "pi" => out.push_str(&omp_body(quirk.id)),
        _ => {}
    }
    out
}

const OPENCODE_BODY: &str = r#"export const StaterootHooks = async ({ directory }: { directory: string }) => ({
  event: async (input: any) => {
    const event = input?.event;
    const properties = event?.properties ?? {};
    if (event?.type === "session.created") hook("session_start", { cwd: directory, ...properties });
    if (event?.type === "session.idle") hook("stop", { cwd: directory, ...properties });
    if (event?.type === "session.deleted") hook("session_end", { cwd: directory, ...properties });
    if (event?.type === "session.compacted") hook("pre_compact", { cwd: directory, ...properties });
  },
  "chat.message": async (input: any, output: any) => {
    hook("user_prompt_submit", {
      cwd: directory,
      agent: input?.agent,
      model: input?.model,
      messageID: input?.messageID,
      parts: output?.parts,
    });
  },
  "tool.execute.before": async (input: any, output: any) => {
    hook("pre_tool_use", { cwd: directory, tool: input?.tool, callID: input?.callID, args: output?.args });
  },
  "tool.execute.after": async (input: any, output: any) => {
    hook("post_tool_use", {
      cwd: directory,
      tool: input?.tool,
      callID: input?.callID,
      args: input?.args,
      output: output?.output,
      metadata: output?.metadata,
    });
  },
  "experimental.session.compacting": async () => {
    hook("pre_compact", { cwd: directory });
  },
  dispose: async () => {
    hook("session_end", { cwd: directory });
  },
});

export default StaterootHooks;
"#;

fn omp_body(id: &str) -> String {
    let arg = if id == "pi" { "pi" } else { "api" };
    format!(
        r#"export default function StaterootExtension({arg}: any): void {{
  {arg}.on("session_start", (_event: any, ctx: any) => hook("session_start", ctx));
  {arg}.on("before_agent_start", (event: any, ctx: any) => hook("user_prompt_submit", {{ ...ctx, prompt: event?.prompt }}));
  {arg}.on("tool_call", (event: any, ctx: any) => hook("pre_tool_use", {{ ...ctx, tool: event?.toolName, callID: event?.toolCallId, args: event?.input }}));
  {arg}.on("tool_result", (event: any, ctx: any) => hook("post_tool_use", {{ ...ctx, tool: event?.toolName, callID: event?.toolCallId, output: event?.content, isError: event?.isError }}));
  {arg}.on("session_before_compact", (_event: any, ctx: any) => hook("pre_compact", ctx));
  {arg}.on("session_shutdown", (_event: any, ctx: any) => hook("session_end", ctx));
}}
"#
    )
}

/// Install the TS plugin for a Tier B harness (idempotent). Product paths
/// named `stateroot.ts` are always reclaimed; unmarked foreign files at other
/// paths are left alone.
pub fn install_ts_plugin(home: &Path, quirk: &HarnessQuirk) -> Result<Vec<String>, HarnessError> {
    let Some(rel) = ts_plugin_path(quirk) else {
        return Ok(Vec::new());
    };
    let path = home.join(rel);
    let content = render_ts_plugin(quirk);
    let is_product_path = path
        .file_name()
        .and_then(|n| n.to_str())
        .is_some_and(|n| n == "stateroot.ts");
    if path.is_file() {
        let existing = std::fs::read_to_string(&path).map_err(io_err(&path))?;
        if existing == content {
            return Ok(vec![format!(
                "plugin already up to date ({})",
                path.display()
            )]);
        }
        if !is_product_path && !existing.contains(MANAGED_MARKER) {
            return Ok(vec![format!(
                "plugin NOT overwritten (foreign file present): {}",
                path.display()
            )]);
        }
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(io_err(parent))?;
    }
    std::fs::write(&path, content).map_err(io_err(&path))?;
    Ok(vec![format!("plugin → {}", path.display())])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::harness_install::registry::quirk;

    #[test]
    fn opencode_plugin_shape() {
        let src = render_ts_plugin(quirk("opencode").expect("q"));
        assert!(src.contains(MANAGED_MARKER));
        assert!(src.contains("STATEROOT_BIN"));
        assert!(src.contains("[\"hook\", event, \"--harness\", \"opencode\"]"));
        assert!(src.contains("export const StaterootHooks"));
        assert!(src.contains("export default StaterootHooks"));
        assert!(src.contains("session.created"));
        assert!(src.contains("chat.message"));
        assert!(src.contains("tool.execute.before"));
        assert!(src.contains("tool.execute.after"));
        assert!(src.contains("experimental.session.compacting"));
        assert!(src.contains("\"session_start\""));
        assert!(src.contains("\"user_prompt_submit\""));
        assert!(src.contains("\"pre_compact\""));
    }

    #[test]
    fn omp_plugin_shape() {
        let src = render_ts_plugin(quirk("omp").expect("q"));
        assert!(src.contains("export default function StaterootExtension(api: any)"));
        assert!(src.contains("api.on(\"session_start\""));
        assert!(src.contains("api.on(\"before_agent_start\""));
        assert!(src.contains("api.on(\"tool_call\""));
        assert!(src.contains("api.on(\"tool_result\""));
        assert!(src.contains("api.on(\"session_before_compact\""));
        assert!(src.contains("api.on(\"session_shutdown\""));
        assert!(src.contains("--harness\", \"omp\""));
    }

    #[test]
    fn pi_plugin_uses_pi_argument() {
        let src = render_ts_plugin(quirk("pi").expect("q"));
        assert!(src.contains("export default function StaterootExtension(pi: any)"));
        assert!(src.contains("pi.on(\"session_start\""));
        assert!(src.contains("--harness\", \"pi\""));
        assert!(!src.contains(".omp"));
    }

    #[test]
    fn install_is_idempotent_and_reclaims_product_path() {
        let home = tempfile::tempdir().expect("home");
        let q = quirk("opencode").expect("q");
        let first = install_ts_plugin(home.path(), q).expect("install");
        assert!(first.iter().any(|a| a.contains("plugin →")));
        let second = install_ts_plugin(home.path(), q).expect("reinstall");
        assert!(second.iter().any(|a| a.contains("already up to date")));
        // Product path stateroot.ts is always reclaimed.
        let path = home.path().join(ts_plugin_path(q).expect("path"));
        std::fs::write(&path, "// somebody else's plugin\n").expect("foreign");
        let third = install_ts_plugin(home.path(), q).expect("reclaim run");
        assert!(third.iter().any(|a| a.contains("plugin →")));
        let content = std::fs::read_to_string(&path).expect("read");
        assert!(content.contains(MANAGED_MARKER));
        assert!(!content.contains("somebody else's plugin"));
    }
}
